name: Deploy on master branch push

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pages: write
  id-token: write  # This permission is required for deploy-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: 1.18
          otp-version: 27

      - name: Install dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get

      - name: Build project
        run: |
          mix build

      - name: Create CNAME file
        run: echo "www.milkonaut.com" > output/CNAME

      - name: Upload artifact for deployment
        uses: actions/upload-pages-artifact@v1
        with:
          path: output

  pages:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1


